#!/usr/bin/env bash

binary=${1:-/usr/bin/task}

# Check what kind of tasks we have
task overdue >> /dev/null 2>&1
if [ $? -eq 0 ]; then
  overdueTasks=$(task overdue | tail -n +4 | head -n -2 | sed 's/^ //' | cut -d ' ' -f1 | xargs)

  for task in ${overdueTasks}; do
    overdueDisplay="Overdue: [ ${$task} ] $(task _get ${task}.description)"
  done
fi

task active >> /dev/null 2>&1
if [ $? -eq 0 ]; then
  activeTasks=$(task active | tail -n +4 | head -n -2 | sed 's/^ //' | cut -d ' ' -f1 | xargs)

  for task in ${activeTasks}; do
    activeDisplay="Active: [ ${task} ] $(task _get ${task}.description)"
  done
fi

task next >> /dev/null 2>&1
if [ $? -eq 0 ]; then
  upcomingTasks=$(task next | tail -n +4 | head -n -2 | sed 's/^ //' | cut -d ' ' -f1 | head -n 1| xargs)

  for task in ${upcomingTasks}; do
    upcomingDisplay="Next: [ ${task} ] $(task _get ${task}.description)"
  done
fi

if [ ${#activeDisplay} -gt 0 ]; then
  if [ ${#overdueDisplay} -gt 0 ]; then
    echo "${activeDisplay} You have overdue tasks"
  else
    echo ${activeDisplay}
  fi
else
  if [ ${#overdueDisplay} -gt 0 ]; then
    echo "You have overdue tasks"
  else
    if [ ${#upcomingDisplay} -gt 0 ]; then
      echo ${upcomingDisplay}
    fi
  fi
fi

