#!/usr/bin/env bash

mapfile -t < <(find /sys/class/drm/card0/ -name "card0-DP*") dp_inputs
declare docked=false
declare counter=0
declare monitor1=DP-1-1
declare monitor2=DP-2-2

get_monitor_ids() {
    readarray -t monitors  < <(xrandr | grep -w 'connected' | grep -v 'eD' | sort | awk '{print $1}')
    laptop=$(xrandr | grep 'eD' | awk '{print $1}')
    monitor1="${monitors[0]}"
    monitor2="${monitors[1]}"
}

set_docked_status() {
	for output in "${dp_inputs[@]}"; do
		op=$(<"${output}/status")
		if [ "connected" == "${op}" ]; then
			((counter++))
		fi
	done

	if [ "${counter}" -ge 2 ]; then
		docked=true
	fi
}

send_notification() {
	notify-send --urgency=low -t 5000 "DPI has been changed, restart your applications for it take effect."
}

update_xresources_dpi() {
	local dpi="$1"
	sed -i -E --follow-symlinks "s/^#define DPI.+/#define DPI ${dpi}/" ~/.Xresources
}

merge_xresources() {
	xrdb -merge ~/.Xresources
}

update_screen_layout() {
  local docked="$1"
  if [ "${docked}" == true ]; then
        xrandr --output "${monitor1}" --auto --primary --output "${monitor2}" --auto --right-of "${monitor1}" --output "${laptop}" --off
        xinput disable "AT Translated Set 2 keyboard"
  else
        xrandr --output "${laptop}" --auto --primary
        xinput enable "AT Translated Set 2 keyboard"
  fi

}

main() {
  local dpi=168
  get_monitor_ids
	set_docked_status

	if [ "${docked}" == true ]; then
	  dpi=96
  else
    dpi=168
  fi

  update_xresources_dpi "$dpi"
  update_screen_layout "$docked"
  merge_xresources
  setxkbmap se -option caps:escape
  xrandr --dpi "$dpi"
  i3-msg restart
  send_notification

}

main
