#!/bin/bash
if [[ ! -z "$RUNNING_X" ]]; then 
    i3-msg 'exec --no-startup-id alacritty --class scratchpad --title scratchpad'
else
    swaymsg 'exec --no-startup-id alacritty --class scratchpad --title scratchpad'
fi
